<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_--None--Case Reason</name>
   <tag></tag>
   <elementGuidId>36fc71c8-7efb-472f-95d8-49ee82516e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/span[text()='Case Reason']/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da5e1b6f-fc36-4bd6-8810-b4f6b317bd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd45da77-a913-41b0-9ab5-b214b213ad77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1b0750c-40cb-4d5e-aa88-a421f1b2f77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>17171:0-label</value>
      <webElementGuid>eaceb14a-c41d-4c99-91fb-87ad36b184ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6447b68e-854d-4a4e-a613-df2d08e07236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d182a511-2518-4d15-a963-638c124c3ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>27b7cdc3-6342-493f-997c-fedbe5aa1eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8f8ee588-295a-4bcf-be5b-b89e2816f19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>17181:0</value>
      <webElementGuid>ff966dd9-25ab-4d5e-9b44-c1417667056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>96de9a9e-7f36-4d3d-90fd-e3ab0caf9a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>211</value>
      <webElementGuid>805c87aa-4ac4-4f5c-af17-b12ebb6949ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--</value>
      <webElementGuid>553f8d36-c123-446a-8dd0-8901ef426a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17178:0&quot;)/div[1]/div[1]/a[@class=&quot;select&quot;]</value>
      <webElementGuid>e45d97d9-faf6-4a1c-82ba-0e09a9069ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[2]/following::a[1]</value>
      <webElementGuid>cbbf98be-ec38-4698-b412-ac759ff00bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escalated'])[1]/following::a[1]</value>
      <webElementGuid>8d58a4dd-950e-444c-92fe-94df2d8a84fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Origin'])[2]/preceding::a[1]</value>
      <webElementGuid>ed11b9e0-c9cb-45b0-a3e5-26530d32f025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::a[1]</value>
      <webElementGuid>ed072a0c-282b-4372-baa2-1b950288041a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@role = 'button' and @class = 'select' and @href = 'javascript:void(0);' and (text() = '--None--' or . = '--None--')]</value>
      <webElementGuid>4b1e91fd-4922-40f9-8ebf-96b8551fc861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='17178:0']/div/div/a</value>
      <webElementGuid>b2f30c6d-4d69-475a-a161-b50d2315838e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'--None--')]</value>
      <webElementGuid>2132a07e-d8b8-4260-a583-ce3a3549e7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[36]</value>
      <webElementGuid>7af32c4f-b252-4fa1-b617-37a2a92ba219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>8e7c4573-e7f7-4c98-a5eb-bc465845f04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
