<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Request_Date_and_Time__c</name>
   <tag></tag>
   <elementGuidId>80ce8257-8892-40c4-85fe-3452936a819d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-418</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'Request_Date_and_Time__c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f7535d4-bc60-4522-9afc-4a512de8d5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>ccc6a87a-ddb4-4b7b-bb1c-ff04785c965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abd0719a-5cdd-4032-832a-0b8492bf886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-418</value>
      <webElementGuid>cb3003bd-5760-4d1f-b55d-2ad5794e5290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Request_Date_and_Time__c</value>
      <webElementGuid>52eb38f0-b183-4703-823b-05bebfa56309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0c9c06bf-94d8-47d7-a87c-0b916cf4eee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-418&quot;)</value>
      <webElementGuid>bdb129c0-661f-4795-889f-9a75d96cabbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Request_Date_and_Time__c']</value>
      <webElementGuid>6f4fc5d4-b855-4b03-9867-d75b99f3405c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-418']</value>
      <webElementGuid>92d2292b-d5b4-4174-a59c-69f6c6f7f903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-395']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-input-date-time/lightning-input/lightning-datetimepicker/div/fieldset/div/div/div/lightning-datepicker/div/div/input</value>
      <webElementGuid>b43a4d06-bb45-4a9d-93f8-7522d444d7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>91f29c19-00d8-46b4-9102-d0c302160522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
