<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_(GMT1400) Apia_50c48d</name>
   <tag></tag>
   <elementGuidId>fcecd1b5-229b-4521-a5c8-2283074d7218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-437-1-437</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[(text() = '(GMT+14:00) Apia Daylight Time (Pacific/Apia)' or . = '(GMT+14:00) Apia Daylight Time (Pacific/Apia)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>0c2cbbff-3273-4172-8f7f-0a03ea36bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>686414ee-0bd4-470f-8018-ece0c8cd702c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-437-1</value>
      <webElementGuid>4433ecd3-f99f-4e6d-b376-cd3ed4bea9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>(GMT+14:00) Apia Daylight Time (Pacific/Apia)</value>
      <webElementGuid>cab5338a-aff2-424a-a527-51f18df1d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0ef1c339-c5cd-42f5-871b-75086ccb62c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-437-1-437</value>
      <webElementGuid>d28a4ec9-d7cd-4687-ae53-e54fb3c49d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e25bdf26-6cea-4453-b85e-33f1669e2c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ac24fb9-ecb7-4ac6-af88-10c377793b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(GMT+14:00) Apia Daylight Time (Pacific/Apia)</value>
      <webElementGuid>06678562-a9e5-4c71-859e-4fedd446ac81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-437-1-437&quot;)</value>
      <webElementGuid>8f0c5217-aa74-4675-b72f-c9405291d993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[(text() = '(GMT+14:00) Apia Daylight Time (Pacific/Apia)' or . = '(GMT+14:00) Apia Daylight Time (Pacific/Apia)')]</value>
      <webElementGuid>659c2296-de4b-451b-9f55-9cc369713b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[5]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>3f56599c-4998-4fe7-b989-877a97139e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[4]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>1a82c11b-676e-4446-a894-06f3b6b7e67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(GMT+14:00) Line Islands Time (Pacific/Kiritimati)'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>087276be-edfc-4594-9c3c-ec91d1bcfab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-437-1-437']</value>
      <webElementGuid>a9283b41-e2f8-420f-8ac9-b0c341659d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-437']/lightning-base-combobox-item[2]</value>
      <webElementGuid>4a69f0de-0b27-404e-b037-63f493394efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[3]/slot/records-record-layout-item/div/span/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/lightning-base-combobox/div/div[2]/lightning-base-combobox-item[2]</value>
      <webElementGuid>92da44bf-6bf6-489d-88af-aa7217c2e53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
