<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__36160</name>
   <tag></tag>
   <elementGuidId>e42e3d96-a0f0-4209-8e5f-5f3f97668a16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Last Name' and @type = 'text' and @class = 'lastName compoundBorderBottom form-element__row input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6af68043-a841-42da-8d61-ae431dc9233d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>91df1915-0ad0-4560-824e-565bb6eeddb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3616:0</value>
      <webElementGuid>ed79d029-3f9a-4fac-85fe-c1d69f90b168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>e3522e2e-bd9b-4891-8f4f-27b0ea9feb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3524651-1716-4f83-befa-a4ebda820970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lastName compoundBorderBottom form-element__row input</value>
      <webElementGuid>c273a026-4977-49fd-b4e4-8534eb5db7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3620:0</value>
      <webElementGuid>af129a2f-eabe-42ba-aa6a-8f165e4baa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1cf5a825-c34b-4167-bcb3-5646e0f54613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15de95f7-e868-4718-9f91-1316f96d06cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3616:0&quot;)</value>
      <webElementGuid>e10ff481-ee0e-4d12-989d-d02ef0640425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3616:0' and @placeholder = 'Last Name' and @type = 'text' and @class = 'lastName compoundBorderBottom form-element__row input']</value>
      <webElementGuid>6dbd700e-5d05-45b0-8069-20144c494a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3616:0']</value>
      <webElementGuid>ac7ed071-515d-4eda-a331-b32546ac112a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3455:0']/div/div/div/div/div/fieldset/div/div[4]/input</value>
      <webElementGuid>fea9fa29-33d4-4533-8839-b005cfbe9480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a05a127d-2bca-4547-b950-3cd7adf6f931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
