<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Web</name>
   <tag></tag>
   <elementGuidId>4aa2afba-cb31-4a74-bf67-4aa0efe512d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.slds-media__body > span.slds-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df1e06f6-6ca8-498a-8094-31818a771f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>bddd49bd-53cc-437e-91c8-d82883099162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>e48c79b6-12a2-4cbf-b55b-b42137cf44ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>5324a35a-7595-447a-b753-7e7b9686e0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;source-list-479&quot;)/li[@class=&quot;slds-listbox__item&quot;]/div[@class=&quot;slds-listbox__option slds-listbox__option_plain slds-media slds-media_small slds-media_inline slds-is-selected&quot;]/span[@class=&quot;slds-media__body&quot;]/span[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>c93b75fa-4b31-48bd-8a28-7f1b82ea472b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::span[2]</value>
      <webElementGuid>ceae638f-9ed9-4342-9451-1c7bd03438f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Platforms'])[1]/following::span[3]</value>
      <webElementGuid>9bdf9773-a012-404d-a742-1c0d19a935a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/preceding::span[1]</value>
      <webElementGuid>899579ba-884f-4d5e-a06d-169c368498c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::span[3]</value>
      <webElementGuid>d5ffd020-2671-431d-833a-51e7ace4676b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web']/parent::*</value>
      <webElementGuid>e2211f20-19c4-420c-a750-8fa3c84d7921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'slds-truncate' and @title = 'Web' and (text() = 'Web' or . = 'Web')]</value>
      <webElementGuid>aa4b4d9f-92db-4125-8b14-648e5e3ec8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='source-list-479']/li/div/span/span</value>
      <webElementGuid>6b3341e1-8954-490f-8237-1fc8c06de7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span/span</value>
      <webElementGuid>adf4e0e1-b15c-40cd-a024-e7083005a4b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
