<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View Calendar_sfxdash-iframe2</name>
   <tag></tag>
   <elementGuidId>da7379b1-fff0-45db-81d8-6ec70dd15f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;sfxdash-1670340334332-542841&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@title = 'dashboard']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@title = 'dashboard'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bdd8efa6-3a52-4143-86aa-0909c3bc6edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sfxdash-1670340334332-542841</value>
      <webElementGuid>d2428829-7fd2-43ce-b16b-55f93c9bc81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>7be1d0dc-4b5c-4be0-901e-921335e0b090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.lightning.force.com/desktopDashboards/dashboardApp.app?dashboardId=01Z5D000000EeERUA0&amp;displayMode=edit&amp;networkId=000000000000000&amp;userId=0055D000004N9ctQAC</value>
      <webElementGuid>27c16cc6-5301-41e2-889a-fe7f633e8b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2567ca8-9e1c-48be-8479-aa2125968c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;standalone dashboardTopLevelContainer desktopDashboardsDashboard&quot;]/div[@class=&quot;dashboardContainer&quot;]/iframe[1]</value>
      <webElementGuid>1449dc1f-07e6-462b-968e-43a8afb7e49f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'sfxdash-1670340334332-542841' and @title = 'dashboard' and @src = 'https://katalon-inc--demo.sandbox.lightning.force.com/desktopDashboards/dashboardApp.app?dashboardId=01Z5D000000EeERUA0&amp;displayMode=edit&amp;networkId=000000000000000&amp;userId=0055D000004N9ctQAC']</value>
      <webElementGuid>bca1498e-9594-4c05-b895-8853537beb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='sfxdash-1670340334332-542841']</value>
      <webElementGuid>2ea6b54e-799e-478f-8043-6d3f33f9a10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/div/div[2]/iframe</value>
      <webElementGuid>ce8451fa-c9ed-4552-9fcf-dac1859baad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/iframe</value>
      <webElementGuid>e44b201d-0c3a-4221-bf2a-86c647b6e755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
