<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastName</name>
   <tag></tag>
   <elementGuidId>41d45190-4ee1-43aa-8c16-af5b0848b62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'lastName' and @placeholder = 'Last Name' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-205</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edd0effd-c111-4e30-b9bb-fa0880315a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>cb6719e2-48b7-400e-a2fe-5c5f89edfa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-205</value>
      <webElementGuid>0e527116-5248-43ba-b354-fdb9cca524a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-205</value>
      <webElementGuid>b919c6db-fe09-41d7-8332-7040df35e342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>de1b07ec-99f9-4e8d-b391-216a2b577198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>7c33bcc8-be06-4fe9-ac25-6a58aa205346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6e8b551-1ed3-48b3-b472-095bf8e1aaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>acc12d0b-0084-44e6-b77b-04d74c7db19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fa5537b-0914-4124-a61a-663d02a7b5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-205</value>
      <webElementGuid>c8d418cd-b518-4cb8-b00a-7eb6e0bfbecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-205&quot;)</value>
      <webElementGuid>084d5f32-9bae-410f-b53c-b6dcd89b8d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lastName' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>db255674-61a5-4cd8-b9e7-11ac34c1afb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-205']</value>
      <webElementGuid>fb10e7c0-e91a-4264-bb57-c58e0971bcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-190']/dl/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-input-name/lightning-input-name/fieldset/div/div/div[4]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>96d97180-6632-48d3-8bc0-4c7ff15241c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>abdb88ad-bd6c-4c60-9e47-ad3332c94ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
