<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Case 00001063 was saved</name>
   <tag></tag>
   <elementGuidId>b9aa98d9-7934-4063-8bde-317a6756799a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.toastMessage.slds-text-heading--small.forceActionsText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='success'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8549d3b-aa48-4220-af21-6b54eb3f5e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toastMessage slds-text-heading--small forceActionsText</value>
      <webElementGuid>7c33d5d0-d4e2-4bce-a437-80f1604f3bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>18022:0</value>
      <webElementGuid>da5350a5-7ed6-4232-93d8-81e024dd921a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceActionsText</value>
      <webElementGuid>2c3c81bc-7837-4c9f-a3f3-cd3782d0095b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case &quot;00001063&quot; was saved.</value>
      <webElementGuid>06e2c37b-1280-4024-a668-234012855e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastDescription18009:0&quot;)/span[@class=&quot;toastMessage slds-text-heading--small forceActionsText&quot;]</value>
      <webElementGuid>78392c5d-b723-4316-a9f7-1f5dd8f88187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='success'])[1]/following::span[1]</value>
      <webElementGuid>fa1e352e-f063-4a34-954c-dd73c2b1d0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[4]/following::span[3]</value>
      <webElementGuid>27ca7e50-caf4-42a7-8208-659a815a43ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>c8bd86b8-7852-43ab-9765-984941ef07fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'toastMessage slds-text-heading--small forceActionsText' and (text() = 'Case &quot;00001063&quot; was saved.' or . = 'Case &quot;00001063&quot; was saved.')]</value>
      <webElementGuid>0f1795e4-a6c8-4a8e-94f6-206af0743229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription18009:0']/span</value>
      <webElementGuid>d06e092c-c53f-4dc1-a33d-f4024f9947e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/span</value>
      <webElementGuid>46f76078-80bd-426c-9765-8c025e6107c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
