<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search apps and items_input-347</name>
   <tag></tag>
   <elementGuidId>3be0334b-eba3-4f07-982a-c2c53e713e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-347</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'search' and @placeholder = 'Search apps and items...']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34c2a088-8577-4da9-97bc-f062d2e91460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>09372a69-5bd9-42c4-8d89-aacf80ba6770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6aa0de03-b037-43be-af1a-2b954454ed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-347</value>
      <webElementGuid>6e36f601-2a04-478f-acb4-e1aa13ce0400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36567f25-434c-4519-ad46-65752721ebbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-347</value>
      <webElementGuid>359c3007-54f7-4254-a15d-e34fe272229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search apps and items...</value>
      <webElementGuid>e94f238d-6155-4263-b6e2-446500b0ec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c8ca19ee-15fc-4390-9226-78226ea5b180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>63171042-4c46-4c2b-9375-63658de390e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>91319955-14f1-479a-9362-7bf20d7e854b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>al-menu-dropdown-apps-id-345</value>
      <webElementGuid>d5a7c9d5-e559-4029-a75b-ada5f907f4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a69a632-3d81-4e61-8411-90331d3a96ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-347&quot;)</value>
      <webElementGuid>6845b913-f761-48be-9901-5ee3f41fcea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search apps and items...']</value>
      <webElementGuid>9cbac244-f126-4334-8cbb-75bf886de4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-347']</value>
      <webElementGuid>2191abec-b910-49e6-bdf8-3c09bc2aa070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_4543:0']/one-app-launcher-menu/div/one-app-launcher-search-bar/lightning-input/div/div/input</value>
      <webElementGuid>5e1cdc5f-65cf-48af-927b-a5eb35cfd119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-search-bar/lightning-input/div/div/input</value>
      <webElementGuid>fcde92db-e8f4-40b3-a8a0-96340a9f6978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
