<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mohit Kuma_icon</name>
   <tag></tag>
   <elementGuidId>1ff0c7b3-e213-4777-ba43-08263b524044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[contains(@title, 'Gokul Sridharan')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b7f076e1-f5cf-45a2-806d-3102ee98c49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>6:2347;a</value>
      <webElementGuid>79aae25c-1247-48b3-9d5e-a324906a3637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png</value>
      <webElementGuid>e23718d6-c31e-4992-86aa-f814be8d4c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon </value>
      <webElementGuid>27f49440-1a8f-4708-a1ad-0e0d7ef8f891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>e6c64c24-1555-49ca-8c0d-efbc7b5a5b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>c281ca76-89b0-46b3-807b-e92f0c09284a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1:2347;a&quot;)/div[@class=&quot;mruIcon slds-icon slds-icon--small slds-float--left slds-m-vertical--xx-small slds-m-left--xx-small slds-media__figure forceEntityIcon&quot;]/span[@class=&quot;uiImage&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>a8c36d45-3428-44f5-a643-671f093079b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1:2347;a']/div/span/img</value>
      <webElementGuid>8d1d0833-7569-4cd4-a1ae-a778884ca4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='User'])[3]</value>
      <webElementGuid>29294604-ff73-4d9d-8554-9198beff6232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span/img</value>
      <webElementGuid>f410ef57-9264-414e-9c04-58f14437fd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png' and @class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      <webElementGuid>02c72412-a2be-4b8d-ade6-7fc9dd1b0ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
