<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mohit Kuma_icon</name>
   <tag></tag>
   <elementGuidId>1ff0c7b3-e213-4777-ba43-08263b524044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[contains(@title, 'Bhagyesh Nanwani')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f81fc59-25e2-465d-ad7b-485ab77f6c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>6:2347;a</value>
      <webElementGuid>3d9e2d43-77fb-4a3c-b970-9ab62c5e4032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png</value>
      <webElementGuid>712aec0f-c60b-4820-88f3-10a844ca31d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon </value>
      <webElementGuid>2c123ccc-1ad7-4dc9-ba99-6e4e919f7754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>e751af13-5878-467f-9bcf-d2578f408f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>1907ca92-8ecd-4dbc-a968-8fade12089a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1:2347;a&quot;)/div[@class=&quot;mruIcon slds-icon slds-icon--small slds-float--left slds-m-vertical--xx-small slds-m-left--xx-small slds-media__figure forceEntityIcon&quot;]/span[@class=&quot;uiImage&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>bb25c332-9c51-48b6-9851-e5015f60e13e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1:2347;a']/div/span/img</value>
      <webElementGuid>a52a2e07-efa8-45cb-bba8-7ae676a13ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='User'])[3]</value>
      <webElementGuid>dc12c8a4-2b5a-41a1-a2be-d332d4f6d4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span/img</value>
      <webElementGuid>00b790cc-2715-4aa7-a236-6394a66a06ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png' and @class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      <webElementGuid>53fe9c0e-7a33-44f1-a371-4b1c3fbddd29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
