<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_500BS000006tnXiYAI</name>
   <tag></tag>
   <elementGuidId>60ccfc1c-3661-4115-9dfb-3b4644186731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;500BS000006tnXiYAI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title = '500BS000006tnXiYAI' and (text() = '500BS000006tnXiYAI' or . = '500BS000006tnXiYAI')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e30a0848-4a81-4a5f-85c6-49bb43f81434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>500BS000006tnXiYAI</value>
      <webElementGuid>da4abba8-740c-4080-9b5c-4cddacf92ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1522:0</value>
      <webElementGuid>4c657f78-ee47-4aae-ad2d-c3ff559a92ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>500BS000006tnXiYAI</value>
      <webElementGuid>c7596256-b1e7-481a-ba9b-3605fae031be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastDescription1485:0&quot;)/span[@class=&quot;toastMessage slds-text-heading--small forceActionsText&quot;]/a[@class=&quot;forceActionLink&quot;]/div[1]</value>
      <webElementGuid>78bbd170-a391-4205-ba9c-713f9afd6ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '500BS000006tnXiYAI' and (text() = '500BS000006tnXiYAI' or . = '500BS000006tnXiYAI')]</value>
      <webElementGuid>1efba32e-c47e-4de6-a3aa-26d6ab9ff9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::div[4]</value>
      <webElementGuid>2330f557-5663-4c25-b401-6b8903a82eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[1]</value>
      <webElementGuid>70e9b90a-cdbc-4e82-92eb-db943972ba4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='500BS000006tnXiYAI']/parent::*</value>
      <webElementGuid>89795572-1f8d-4610-9fcd-5ad4476f06ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription1485:0']/span/a/div</value>
      <webElementGuid>4c2b5afb-479d-44f4-922a-a228c96083b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/div</value>
      <webElementGuid>21c501c3-069a-418f-8203-b6c8ac6bd430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
