<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Change Case Owner</name>
   <tag></tag>
   <elementGuidId>b9d91832-f611-4341-b545-c828366c2bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[(text() = 'Change Case Owner' or . = 'Change Case Owner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ae3966e8-2f66-42d1-bf49-68828c226a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_2467:0</value>
      <webElementGuid>c569c8a2-1286-4e5e-bd8d-37e5c88aa8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title slds-text-heading--medium slds-hyphenate</value>
      <webElementGuid>ba2d7042-e426-4c77-9863-dccc2315bcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2487:0</value>
      <webElementGuid>29a34b3a-a4f2-41ba-88f3-368df7e03947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change Case Owner</value>
      <webElementGuid>ef3b2bd0-5bac-408c-8741-f784fd2e1e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_2467:0&quot;)</value>
      <webElementGuid>4265030b-110a-46f3-be46-b643fc4beaef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Change Case Owner' or . = 'Change Case Owner')]</value>
      <webElementGuid>91a1340a-5019-4045-9aff-be5752247e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View profile'])[2]/following::h2[1]</value>
      <webElementGuid>1a1098d5-7184-4542-9d6d-227c3c0a8769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/following::h2[1]</value>
      <webElementGuid>839c1257-472f-452a-a7f4-063718c7b9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close this window'])[1]/preceding::h2[1]</value>
      <webElementGuid>4d98a44e-3036-4648-a135-43a4210beb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick an object'])[1]/preceding::h2[1]</value>
      <webElementGuid>98f4fe09-c8ca-4018-93c4-a1b8078ab93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change Case Owner']/parent::*</value>
      <webElementGuid>b4aaffc0-6fb6-4167-b4ee-6ce7ea0b4011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='title_2467:0']</value>
      <webElementGuid>ad1b39bb-c1a1-4b28-b1ce-551efc0b7aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h2</value>
      <webElementGuid>927da711-76a0-412e-bd05-3d615a0d0799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
