<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>dabe12fb-4f6a-43a6-9b08-d786e1542c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.slds-icon_container.slds-icon-utility-down > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[@title='${caseNo}']//following::td[11]//a[@role='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfcb5030-5b21-4edf-a008-2a401b235d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7307:0</value>
      <webElementGuid>03400e8a-c615-4f55-8d5a-4770d0ba6b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;slds-grid forceSearchBaseSearchPage forceSearchSearchPageDesktop&quot;]/div[@class=&quot;searchScrollerWrapper&quot;]/div[@class=&quot;resultsWrapper slds-template__content slds-scrollable--y&quot;]/div[@class=&quot;forceSearchResultsRegion slds-grid slds-grid--vertical&quot;]/div[@class=&quot;predictedResultsOuterWrapper slds-grid slds-grid_vertical slds-col slds-is-relative forceSearchPredictedResults&quot;]/div[@class=&quot;predictedResultsWrapper slds-grid slds-grid_vertical slds-col slds-is-relative slds-m-bottom_medium&quot;]/div[@class=&quot;enabled uiScroller forceSearchResultsMultiScope scroller-wrapper scroll-vertical native&quot;]/div[@class=&quot;scroller&quot;]/div[@class=&quot;resultsMultiWrapper&quot;]/div[@class=&quot;slds-grid slds-grid_vertical&quot;]/div[@class=&quot;resultsItem slds-col slds-no-flex slds-m-bottom_small&quot;]/div[@class=&quot;forcesearch-results-grid-lvm-desktop slds-table_joined  test-listViewManager slds-card slds-card_boundary slds-grid slds-grid--vertical forceListViewManager forceSearchResultsGridLVM&quot;]/div[@class=&quot;slds-grid listDisplays safari-workaround-anchor&quot;]/div[@class=&quot;listViewContainer safari-workaround&quot;]/div[@class=&quot;slds-col slds-no-space forceListViewManagerPrimaryDisplayManager&quot;]/div[@class=&quot;autoHeight col-0-wrap col-1-wrap col-2-wrap col-3-wrap col-4-wrap col-5-wrap col-6-wrap col-7-wrap col-8-wrap col-9-wrap hideRowNumberColumn hideSelection forceListViewManagerGrid&quot;]/div[@class=&quot;listViewContent slds-table--header-fixed_container&quot;]/div[@class=&quot;uiScroller scroller-wrapper scroll-bidirectional native&quot;]/div[@class=&quot;scroller actionBarPlugin&quot;]/div[@class=&quot;slds-table--edit_container slds-is-relative  inlineEdit--disabled keyboardMode--active inlineEditGrid forceInlineEditGrid&quot;]/table[@class=&quot;slds-table forceRecordLayout slds-table--header-fixed slds-table--edit slds-table--bordered resizable-cols slds-table--resizable-cols uiVirtualDataTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;slds-cell-edit cellContainer&quot;]/span[@class=&quot;slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;forceVirtualActionMarker forceVirtualAction&quot;]/a[@class=&quot;rowActionsPlaceHolder slds-button slds-button--icon-x-small slds-button--icon-border-filled keyboardMode--trigger&quot;]/span[@class=&quot;slds-icon_container slds-icon-utility-down&quot;]/span[1]</value>
      <webElementGuid>76ce2653-2464-4167-a648-e8ebb38527ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohit'])[2]/following::span[15]</value>
      <webElementGuid>a2b5c7cf-d825-4ae4-8f0a-7ce52b45a544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//table[@role='grid']//following::td//a[@role='button']//*[local-name()='svg'])[3]</value>
      <webElementGuid>43790fe4-4fdc-46d6-ad7d-8a40ad9ab43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//table[@role='grid']//following::td//a[@role='button'])</value>
      <webElementGuid>92ae4a7f-845d-45cd-84f3-bbc9755846ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>76f697c6-34eb-432d-8546-303ddb77d1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[11]/span/div/a/span/span</value>
      <webElementGuid>4504fa4e-858f-416f-a825-de296aac88a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span/span</value>
      <webElementGuid>794b6743-f4b7-42ff-a0a8-11e971dd0141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
