<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Show more actions</name>
   <tag></tag>
   <elementGuidId>8a769f79-ec28-4f2f-ba6e-bf9dc3df473a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@class='slds-icon_container slds-icon-utility-down']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.slds-button.slds-button--icon-x-small.slds-button--icon-border-filled</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'button' and (text() = 'Show more actions' or . = 'Show more actions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>923f26a8-d255-4c13-86b4-696d6cc9e4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1aa3041a-6f42-4496-b82e-862959007ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c2ede2c-a590-4ec5-9ffc-4ef8b285a473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4729fdb-23e7-411c-a440-96808959dbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85dcc934-3540-4233-b9f8-49e42b812f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show 4 more actions</value>
      <webElementGuid>81533dd6-b198-4fd6-898a-ba2ea968a081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button--icon-x-small slds-button--icon-border-filled</value>
      <webElementGuid>c53c9e8b-8191-4005-8214-990a6dff1d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1772:0</value>
      <webElementGuid>ad0c81ec-5942-474e-8d9e-90ca9ffe9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>98b5f504-0577-4bcd-b088-b629f4b01bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37f8fac2-95b8-4509-8494-65b359d25eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show more actions</value>
      <webElementGuid>be45c0c7-d910-4f91-891b-368a883250fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1778:0&quot;)/div[1]/a[@class=&quot;slds-button slds-button--icon-x-small slds-button--icon-border-filled&quot;]</value>
      <webElementGuid>0ff0a60c-076d-4527-92d4-f36988029421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Show 4 more actions' and @href = 'javascript:void(0);' and (text() = 'Show more actions' or . = 'Show more actions')]</value>
      <webElementGuid>3fa57f85-0f4d-49c8-b47d-d5fe6ae9639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locked Owner Alias: Item'])[1]/following::a[1]</value>
      <webElementGuid>2eb3e728-528d-4f04-87f6-25612a6ec64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bnanw'])[1]/following::a[1]</value>
      <webElementGuid>1dd5aeac-9058-4acc-b263-3f9210a75a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You haven', &quot;'&quot;, 't viewed any Leads recently.')])[1]/preceding::a[1]</value>
      <webElementGuid>ed4fa413-92c7-4b97-af9c-4ed465669ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1778:0']/div/a</value>
      <webElementGuid>0054a5ad-8b84-4f2e-a23f-736d4acb4e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[19]</value>
      <webElementGuid>9426b7b0-2eb8-4b47-95c4-30691a1dacc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/ul/li/div/div/div/div/a</value>
      <webElementGuid>1f818a5d-b87b-4a95-8692-65c3e2308945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
